/** Generated by Video Manager */
const config = {
    title: "电棍otto",
    id: "EV4",
    date: "2025-11-18",
    author: "EllAri",
    videoSrc: "/vid/EV4.mp4",
    poster: "", 
    description: "大家好啊，我是说的道理，\n今天来点大家想看的东西。",
    sidebarCards: [
    {
        "title": "哇袄",
        "content": "114514"
    },
    {
        "title": "哇袄",
        "content": "1919810"
    }
]
};